### ISSUE TITLE
panic: connection is already registered with serial X

### ISSUE THREAD

**Issue by schu** [canonical/go-dqlite#10]
I randomly(?) encounter the following panic with LXD currently:

```
panic: connection is already registered with serial 15

goroutine 69 [running]:
github.com/CanonicalLtd/go-dqlite/internal/registry.(*Registry).connAdd(0xc4204d6000, 0x7f10ea49f3f0)
        /home/schu/code/go/src/github.com/CanonicalLtd/go-dqlite/internal/registry/conn.go:136 +0x162
github.com/CanonicalLtd/go-dqlite/internal/registry.(*Registry).ConnLeaderAdd(0xc4204d6000, 0xc42120cd4a, 0x6, 0x7f10ea49f3f0)
        /home/schu/code/go/src/github.com/CanonicalLtd/go-dqlite/internal/registry/conn.go:26 +0x39
github.com/CanonicalLtd/go-dqlite.(*cluster).Register(0xc4201a7900, 0x7f10ea49f3f0)
        /home/schu/code/go/src/github.com/CanonicalLtd/go-dqlite/cluster.go:66 +0x47
github.com/CanonicalLtd/go-dqlite/internal/bindings.clusterRegisterCb(0x64, 0x7f10ea49f3f0)
        /home/schu/code/go/src/github.com/CanonicalLtd/go-dqlite/internal/bindings/cluster.go:207 +0x63
github.com/CanonicalLtd/go-dqlite/internal/bindings._cgoexpwrap_c04adbaf2773_clusterRegisterCb(0x64, 0x7f10ea49f3f0)
        _cgo_gotypes.go:911 +0x35
github.com/CanonicalLtd/go-dqlite/internal/bindings._Cfunc_dqlite_server_run(0x7f10e41f0420, 0x7f1000000000)
        _cgo_gotypes.go:397 +0x49
github.com/CanonicalLtd/go-dqlite/internal/bindings.(*Server).Run.func1(0x7f10e41f0420, 0xc420063f90)
        /home/schu/code/go/src/github.com/CanonicalLtd/go-dqlite/internal/bindings/server.go:136 +0x56
github.com/CanonicalLtd/go-dqlite/internal/bindings.(*Server).Run(0x7f10e41f0420, 0x10324a0, 0x0)
        /home/schu/code/go/src/github.com/CanonicalLtd/go-dqlite/internal/bindings/server.go:136 +0x2f
github.com/CanonicalLtd/go-dqlite.(*Server).run(0xc4204dcfa0)
        /home/schu/code/go/src/github.com/CanonicalLtd/go-dqlite/server.go:131 +0x54
created by github.com/CanonicalLtd/go-dqlite.NewServer
        /home/schu/code/go/src/github.com/CanonicalLtd/go-dqlite/server.go:88 +0x2be
```

My LXD version at the moment is 32ba6b5e14c9c325ed095ba8eb27d270ca6969ec (stable-3.0), built from source.

<details>

LXD log before the panic:

```
[...]
DBUG[08-12|11:17:43] handling                                 ip=@ method=GET url=/1.0/images/44b8e3990ae1b339887b24bfdf5efddfff80f9057bfa16e8f2ecba69bd5b7165                                                     
DBUG[08-12|11:17:43] Database error: &errors.errorString{s:"sql: no rows in result set"}
DBUG[08-12|11:17:43] handling                                 ip=@ method=GET url=/1.0/events
DBUG[08-12|11:17:43] New event listener: db8c929d-905b-4c33-af4d-dc130cce9f39
DBUG[08-12|11:17:43] handling                                 ip=@ method=POST url=/1.0/containers
DBUG[08-12|11:17:43] Responding to container create                                                  
INFO[08-12|11:17:48] Dqlite: closing client                                                          
DBUG[08-12|11:17:48] Database error: &errors.errorString{s:"driver: bad connection"}                                                                                                                               
DBUG[08-12|11:17:48] Retry failed db interaction (driver: bad connection)                          
INFO[08-12|11:17:48] Dqlite: handling new connection (fd=26)                       
INFO[08-12|11:17:53] Dqlite: closing client                                         
DBUG[08-12|11:17:53] Dqlite: server connection failed err=failed to send Leader request: failed to receive response: failed to receive header: failed to receive header: read unix @->@00310: i/o timeout address=0
attempt=0                                                                                              
DBUG[08-12|11:17:53] Dqlite: connection failed err=no available dqlite leader server found attempt=0                                                                                                               
INFO[08-12|11:17:59] Dqlite: closing client
DBUG[08-12|11:17:59] Dqlite: server connection failed err=failed to send Leader request: failed to receive response: failed to receive header: failed to receive header: read unix @->@00310: i/o timeout address=0
attempt=1                        
DBUG[08-12|11:17:59] Dqlite: connection failed err=no available dqlite leader server found attempt=1 
INFO[08-12|11:18:04] Dqlite: closing client                                                           
DBUG[08-12|11:18:04] Dqlite: server connection failed err=failed to send Leader request: failed to receive response: failed to receive header: failed to receive header: read unix @->@00310: i/o timeout address=0
attempt=2                                                                                             
DBUG[08-12|11:18:04] Dqlite: connection failed err=no available dqlite leader server found attempt=2
INFO[08-12|11:18:09] Dqlite: closing client                                         
DBUG[08-12|11:18:09] Dqlite: server connection failed err=failed to send Leader request: failed to receive response: failed to receive header: failed to receive header: read unix @->@00310: i/o timeout address=0
attempt=3                                                                           
DBUG[08-12|11:18:09] Dqlite: connection failed err=no available dqlite leader server found attempt=3
INFO[08-12|11:18:15] Dqlite: closing client
DBUG[08-12|11:18:15] Dqlite: server connection failed err=failed to send Leader request: failed to receive response: failed to receive header: failed to receive header: read unix @->@00310: i/o timeout address=0
attempt=4
DBUG[08-12|11:18:15] Dqlite: connection failed err=no available dqlite leader server found attempt=4 
INFO[08-12|11:18:21] Dqlite: closing client 
DBUG[08-12|11:18:21] Dqlite: server connection failed err=failed to send Leader request: failed to receive response: failed to receive header: failed to receive header: read unix @->@00310: i/o timeout address=0 attempt=5 
DBUG[08-12|11:18:21] Dqlite: connection failed err=no available dqlite leader server found attempt=5 
INFO[08-12|11:18:27] Dqlite: closing client 
DBUG[08-12|11:18:27] Dqlite: server connection failed err=failed to send Leader request: failed to receive response: failed to receive header: failed to receive header: read unix @->@00310: i/o timeout address=0 attempt=6 
DBUG[08-12|11:18:27] Dqlite: connection failed err=no available dqlite leader server found attempt=6 
INFO[08-12|11:18:28] Dqlite: handling new connection (fd=25) 
INFO[08-12|11:18:28] Dqlite: handling new connection (fd=26) 
INFO[08-12|11:18:28] Dqlite: handling new connection (fd=25) 
INFO[08-12|11:18:28] Dqlite: handling new connection (fd=26) 
INFO[08-12|11:18:28] Dqlite: handling new connection (fd=25) 
INFO[08-12|11:18:28] Dqlite: handling new connection (fd=26) 
INFO[08-12|11:18:28] Dqlite: handling new connection (fd=25) 
INFO[08-12|11:18:28] Dqlite: connected address=0 attempt=7 
INFO[08-12|11:18:33] Dqlite: closing client 
DBUG[08-12|11:18:33] Database error: &errors.errorString{s:"driver: bad connection"} 
DBUG[08-12|11:18:33] Retry failed db interaction (driver: bad connection) 
INFO[08-12|11:18:33] Dqlite: handling new connection (fd=26) 
INFO[08-12|11:18:34] Dqlite: connected address=0 attempt=0 
```
</details>

**Comment by freeekanayaka** [comment]
This was seen by some LXD developers too. Thanks for the log, it helps. I could not reproduce the issue yet, but will try to figure out what can lead to this situation.
